theme: jekyll-theme-cayman

# Setup
title:        DuHwan Jang's Portpolio
tagline:      portpolio
baseurl:      "https://thinkallofyours.github.io"
paginate:     1

# About/contact
author:       Duhwan Jang
  name:       LandR
  url:        https://thinkallofyours.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown